### ISSUE TITLE
How many modification needed to change backend to Firebase?

### ISSUE THREAD

**Issue by steve21124** [jdisho/Papr#20]
How many modification needed do you think if to use Firebase as backend to store all the data instead of from unsplash?

**Comment by jdisho** [comment]
I am not understanding well.. 
Do you want to change the API endpoints?

**Comment by steve21124** [comment]
sorry. Yes, I want to change the API endpoint. and not using unsplash at all. Is it possible?

**Comment by jdisho** [comment]
Yes, it is possible. 
Change the models, add the new endpoints ([example](https://github.com/jdisho/Papr/blob/develop/Papr/Utils/Enums/Unsplash/UnsplashAPI.swift)) and adapt the services.
