### ISSUE TITLE
Would you pls add some loadingView/toastView/noticeView ?

### ISSUE THREAD

**Issue by zhengyaoyuan** [jdisho/Papr#28]
Thx

**Comment by zhengyaoyuan** [comment]
I am curious about how would you implement... For example，you do sth costs a lot of time, need to add a loadingView, and in the end you need to hide it. It is much like pop view not viewController.

**Comment by zhengyaoyuan** [comment]
In AlertViewModel.swift, you expose Outputs like yesObservable, noObservable,okObservable，how would you use it?

**Comment by jdisho** [comment]
Hi @zhengyaoyuan, 

Regarding to your AlertViewModel question

```swift
let alertViewModel: AlertViewModelType = AlertViewModel(title: "Title", message: "some message...", mode: .yesNo)

alertViewModel.outputs
.yesObservable
.flatMap { ... } // handle the case when you press "yes" in alert

alertViewModel.outputs
.noObservable
.flatMap { ... } // handle the case when you press "no" in alert
```

**Comment by jdisho** [comment]
@zhengyaoyuan Can you be more clear for the first question?

**Comment by zhengyaoyuan** [comment]
I have seen your answer about `alertViewModel`. That is not what I want.  I just want something in term of project structure.
For example, user Click yes button, you may need to notify some other scene to do sth. More specifically, how to communicate between two different scene? Between vc or viewModels?

**Comment by zhengyaoyuan** [comment]
More details about first question.  In some cases, you need to show sth like Activity Indicator. You have to hide it when the work is done. Should I add it to Coodinator？ It is like popView. How should I write it in a more rx way? Thx

**Comment by zhengyaoyuan** [comment]
I have seen your answer about alertViewModel. That is not what I want.  In term of project structure.
For example, user Click yes button, you may need to notify some other page to do sth. More speci

**Comment by zhengyaoyuan** [comment]
In my previous non-Rx code, not so elegant
`
@objc private func onBtnSubmit() {
        guard KKTVTools.checkNetworkConnection() else {
            return
        }
        
        if ReachableViaWWAN == KKTVTools.currentNetworkStatus() {
            // pop noticeView
            let noticeView = Bundle.main.loadNibNamed("KKTVNoticeView", owner: nil, options: nil)![0] as! KKTVNoticeView
            noticeView.showPlainTextNoticeView(withTitle: nil, content: String.LS("Continue?"), cancelButtonTitle: String.LS("cancel"), confirmButtonTitle: String.LS("Continue"), noticeMode: KKTVNoticeMode(rawValue: 0), delegate: nil)
            
            noticeView.buttonClick = { [weak self] noticeView, tag in
                if let strongSelf = self {
                    if tag == 1 {
                        strongSelf.startUpload()
                    }
                    noticeView?.dismissNoticeView()
                }
            }
            
            return
        }

        startUpload()
    }
`
Should this code(noticeView or loadingView) put in vm or service? Could you pls provide some elegant way ?
