### ISSUE TITLE
If internet is offline, refresh never works even after going online

### ISSUE THREAD

**Issue by tosbaha** [jdisho/Papr#33]
1. Start the app with no internet connection.
2. Error comes up.
3. Go online
4. Refresh

Since the subscription is ended, no photos will be emitted.

**Comment by jdisho** [comment]
Hey @tosbaha thanks for reporting this. 
I will have a look asap. However feel free to tackle it if you want 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
