### ISSUE TITLE
Where would you put the code ''tableView.rx.itemSelected''?

### ISSUE THREAD

**Issue by zhengyaoyuan** [jdisho/Papr#34]
Since you have put photoDetailsAction in HomeViewCellModel to transition to photoDetails. Now if I want to use tableView.rx.itemSelected. I have to put it in HomeView layer. Is it a little weird to do similar logic in different layers? One in view, one in cell?
How would you write the code? Thx

**Comment by jdisho** [comment]
Actually there is no similar logic in different layers. I decided to transition to PhotoDetails when the photo is touched. If you prefer to transit in tableView.rx.itemSelected then adapt it a bit so the transition happens only if you select the cell.
