### ISSUE TITLE
Improve UX of photo list

### ISSUE THREAD

**Issue by vaderdan** [jdisho/Papr#43]
I will be cool if we could implement parallax images scroll

https://github.com/jdisho/ParallaxScrolling

(images in each cell moves with different speed than the scroll)

**Comment by jdisho** [comment]
Thanks for the suggestions, we can also implement `ParallaxScrolling`. However, I wanted to implement [`PinterestLayout`](https://github.com/jdisho/Papr/blob/develop/Papr/Custom%20UI/PinterestLayout.swift) in `SearchPhotosViewController`. For some reasons, which I don't know actually, RxDataSources crashes with a custom UICollectionViewLayout 😕
