### ISSUE TITLE
Detail Controller like bug

### ISSUE THREAD

**Issue by vaderdan** [jdisho/Papr#54]
I found this bug
When I like photo in details screen and then go back, the tableview photo stays with unliked

<img src="https://user-images.githubusercontent.com/2633467/46400074-289c6400-c702-11e8-950e-24ea9b6006c6.gif" width="320" />

**Comment by jdisho** [comment]
I am aware of this. We can implement a caching system for this.

**Comment by vaderdan** [comment]
@jdisho wdyt about this idea, to pass `Behaviour/PublishSubject/Variable` of photo to PhotoDetailsViewModel
instead of just photo
```
override init(
        photo: BehaviourSubject<Photo>,
        service: PhotoServiceType = PhotoService(),
        sceneCoordinator: SceneCoordinatorType = SceneCoordinator.shared
        ) {
```
and that way we can update it on one place and it will refresh views everywhere

is it going to cause memory problems this idea
