### ISSUE TITLE
SceneCoodinator.swift=>actualViewController=>return issue

### ISSUE THREAD

**Issue by spiderbob** [jdisho/Papr#62]
Papr/Coodinator/SceneCoodinator.swift

    static func actualViewController(for viewController: UIViewController) -> UIViewController {
        var controller = viewController
        if let tabBarController = controller as? UITabBarController {
            guard let selectedViewController = tabBarController.selectedViewController else {
                return tabBarController
            }
            controller = selectedViewController
        }
        if let navigationController = viewController as? UINavigationController {
            return navigationController.viewControllers.first!
        }
        -return viewController  
        +return controller
    }

**Comment by jdisho** [comment]
Thanks! Can you create a PR? @spiderbob

**Comment by spiderbob** [comment]
PR is created
