### ISSUE TITLE
Replace icons with SFSymbols

### ISSUE THREAD

**Issue by jdisho** [jdisho/Papr#89]
Use `SFSymbols` only for `iOS 13`.

**Comment by serjooo** [comment]
I'm wondering has anyone started working on this?

**Comment by jdisho** [comment]
Not as far as I know. 
I was playing around with SFSymbols in the “support-dark-theme” branch. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by serjooo** [comment]
I'll take care of it 👍🏻
