### ISSUE TITLE
XCode 11.2.1 Compile failed

### ISSUE THREAD

**Issue by HotWordland** [jdisho/Papr#99]
git clone https://github.com/jdisho/Papr.git
cd Papr
pod install
open Papr.xcworkspace

and cmd+R compile failed ?
Has anyone encountered this problem ?

![WeChatd95ec537b27483f5d74721904b51ee12](https://user-images.githubusercontent.com/6984865/69603728-6c64d200-1056-11ea-89bd-c898f47b1d74.png)

**Comment by jdisho** [comment]
Are you still able to replicate this issue? I cannot replicate it even in a fresh clone.

**Comment by HotWordland** [comment]
@jdisho it's OK now thanks~
